; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensymm]
platform = teensy
board = teensymm
framework = arduino
build_flags = 
    ; 1. Force the library to use Teensy 4.x logic
    -D ARDUINO_TEENSY41
    -D CORE_TEENSY
    ; 2. Define the missing cycle counter globally for all library files
    -D "dwt_getCycles()=ARM_DWT_CYCCNT"
lib_deps = 
    https://github.com/luni64/TeensyStep.git
lib_archive = no

monitor_speed = 115200